import { describe, expect, it } from "vitest";

import { createReceiptText } from "./receipt-text";

const participants = [
	{
		amount: 19_000,
		final: 14_500,
		name: "Habib",
	},
	{
		amount: 31_000,
		final: 23_500,
		name: "Budi",
	},
];

function formatRupiah(amount: number) {
	return `Rp${amount.toLocaleString("id-ID")}`;
}

describe("createReceiptText", () => {
	it("creates a complete Indonesian receipt in display order", () => {
		const receipt = createReceiptText({
			formatMoney: formatRupiah,
			labels: {
				generated: "Dibuat dengan aplikasi samarata",
				original: "Harga awal",
				saved: "Hemat",
				totalPayment: "Total pembayaran",
				totalSaved: "Total hemat",
			},
			participants,
			splitLabel: "2 orang · sama rata, sama rasa",
			title: "Makan siang kantor",
			total: 38_000,
			totalSaved: 12_000,
		});

		expect(receipt).toBe(`Makan siang kantor
2 orang · sama rata, sama rasa
#0001

01  Habib  Rp14.500
    Harga awal : Rp19.000
    Hemat : Rp4.500
02  Budi  Rp23.500
    Harga awal : Rp31.000
    Hemat : Rp7.500

Total hemat: Rp12.000
Total pembayaran: Rp38.000

Dibuat dengan aplikasi samarata`);
	});

	it("uses the product name when the title is blank", () => {
		const receipt = createReceiptText({
			formatMoney: (amount) => `$${(amount / 100).toFixed(2)}`,
			labels: {
				generated: "Generated by samarata app",
				original: "Original",
				saved: "Saved",
				totalPayment: "Total payment",
				totalSaved: "Total saved",
			},
			participants: [{ amount: 1_250, final: 1_000, name: "Alex" }],
			splitLabel: "1 person · fair split",
			title: "   ",
			total: 1_000,
			totalSaved: 250,
		});

		expect(receipt).toContain("samarata\n1 person · fair split");
		expect(receipt).toContain("Original : $12.50");
		expect(receipt).toContain("Saved : $2.50");
		expect(receipt).toContain("Total saved: $2.50");
		expect(receipt).toContain("Total payment: $10.00");
	});
});
